import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ctx=vm.createContext({});
vm.runInContext(html.slice(html.indexOf('function normalizeState('),html.indexOf('function normalize(result,')),ctx);
vm.runInContext(html.slice(html.indexOf('function applyReadingPreferences('),html.indexOf('function prefersReduceMotion(')),ctx);
const plain=x=>JSON.parse(JSON.stringify(x));
let saved=ctx.normalizeState({preferences:{largeText:true,reduceMotion:true},lessons:{0:{done:true}}});
for(let i=0;i<3;i++)saved=ctx.normalizeState(plain(saved));
assert.deepEqual(plain(saved.preferences),{largeText:true,reduceMotion:true});
assert.equal(saved.lessons[0].done,true,'préserver la progression');
assert.deepEqual(plain(ctx.normalizeState({preferences:{largeText:'false',reduceMotion:1}}).preferences),{largeText:false,reduceMotion:false});
ctx.state=saved;let writes=0;
ctx.save=()=>{ctx.state=ctx.normalizeState(ctx.state);writes++;};
const status={};ctx.document={documentElement:{dataset:{}},getElementById:()=>status};
ctx.setReadingPreference('largeText',false);
assert.equal(ctx.document.documentElement.dataset.reading,'standard');assert.equal(ctx.document.documentElement.dataset.motion,'reduce');assert.equal(writes,1);
ctx.setReadingPreference('unknown',true);assert.equal(writes,1);
const sessions=[{d:'2026-09-09',lessons:[3]},{d:'2026-09-06',lessons:[1]},{d:'2026-09-07',lessons:[1,2]}];
const initial=JSON.stringify(sessions);
assert.deepEqual(plain(ctx.nextScheduledSession(sessions,'2026-09-07',id=>id===1)),{d:'2026-09-07',lessons:[1,2],remaining:[2]});
assert.equal(JSON.stringify(sessions),initial,'le choix de la séance ne change pas le planning');
assert.equal(ctx.nextScheduledSession(sessions,'2026-09-10',()=>false),null);
assert.equal(ctx.nextScheduledSession(sessions,'2026-09-07',()=>true),null);
assert.equal(ctx.nextScheduledSession(sessions,'2026-09-07',id=>id<3).d,'2026-09-09');
const modules=[{titre:'Bases',lessons:[{id:0},{id:1}]},{titre:'Suite',lessons:[{id:2}]}];
const rows=ctx.moduleProgressData(modules,{0:{done:true},1:{done:true}});
assert.equal(rows[0].done,2);assert.equal(rows[0].next,undefined);assert.equal(rows[1].next,2);
assert.equal(ctx.moduleProgressData(modules,{})[0].next,0,'la première leçon a un id zéro');
console.log('Préférences persistantes, prochaine séance et progression par module : OK.');
