import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ctx=vm.createContext({});
const extract=(start,end)=>html.slice(html.indexOf(start),html.indexOf(end,html.indexOf(start)));
vm.runInContext(extract('function primaryTabFor(','function syncTabUI('),ctx);
for(const name of ['console','defis','practice'])assert.equal(ctx.primaryTabFor(name),'practice');
for(const name of ['notes','collection','entretien','library'])assert.equal(ctx.primaryTabFor(name),'library');
for(const name of ['learn','planning','compte'])assert.equal(ctx.primaryTabFor(name),name);
let exo=false,done=false;
ctx.etapesDe=()=>({exo});ctx.lecCompletee=()=>done;
vm.runInContext(extract('function homeLessonSteps(','function renderHomeHero('),ctx);
assert.equal(ctx.homeLessonSteps(38)[2].locked,true,'quiz fermé tant que l’exercice n’est pas validé');
exo=true;
assert.equal(ctx.homeLessonSteps(38)[1].done,true);
assert.equal(ctx.homeLessonSteps(38)[2].locked,false);
done=true;assert.ok(ctx.homeLessonSteps(38).every(step=>step.done));
let opened;
ctx.isDefiId=id=>typeof id==='string';ctx.openLesson=(...args)=>opened=args;ctx.openChallenge=id=>opened=[id];
vm.runInContext(extract('function openItem(','/* Un plan sauvegardé'),ctx);
ctx.openItem(0,1);assert.deepEqual(opened,[0,1],'leçon zéro et étape exercice conservées');
ctx.openItem(38,2);assert.deepEqual(opened,[38,2],'accès à l’étape quiz');
ctx.openItem('d1',0);assert.deepEqual(opened,['d1'],'les défis gardent leur parcours propre');
const nav=html.slice(html.indexOf('<nav class="tabbar"'),html.indexOf('</nav>',html.indexOf('<nav class="tabbar"')));
assert.deepEqual([...nav.matchAll(/data-tab="([^"]+)"/g)].map(m=>m[1]),['learn','planning','practice','library','compte']);
const states={};let active='';
for(const name of ['learn','planning','practice','library','compte'])states[name]={dataset:{tab:name},classList:{toggle(){}},setAttribute(k,v){this[k]=v;},scrollIntoView(){}};
ctx.document={querySelectorAll:()=>Object.values(states),getElementById:()=>null};ctx.requestAnimationFrame=cb=>cb();
vm.runInContext(extract('function syncTabUI(','function screenForTab('),ctx);
for(const [route,parent] of [['notes','library'],['console','practice'],['planning','planning'],['learn','learn']]){
 ctx.syncTabUI(route);
 assert.deepEqual(Object.entries(states).filter(([,v])=>v.tabIndex===0).map(([key])=>key),[parent]);
 assert.equal(states[parent]['aria-selected'],'true');
}
console.log('Parcours lisible : 5 destinations, regroupement, focus clavier, états et reprise d’étapes : OK.');
