#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(import.meta.dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const serviceWorker = fs.readFileSync(path.join(ROOT, 'sw.js'), 'utf8');
let passed = 0;
let failed = 0;

function assert(condition, label) {
  if (condition) {
    passed++;
    console.log(`  ✓ ${label}`);
  } else {
    failed++;
    console.log(`  ✗ ${label}`);
  }
}

console.log('\n=== Socle de mise en production ===');
const navStart = html.indexOf('<nav class="tabbar"');
const navEnd = html.indexOf('</nav>', navStart);
const nav = html.slice(navStart, navEnd);
const accountStart = html.indexOf("function renderCompte(){");
const accountEnd = html.indexOf('function openLegal(', accountStart);
const account = html.slice(accountStart, accountEnd);
const onboardingStart = html.indexOf('function obFlowHeader(');
const onboardingEnd = html.indexOf('function finishOnboard(', onboardingStart);
const onboarding = html.slice(onboardingStart, onboardingEnd);

assert((nav.match(/class="tab(?: active)?"/g) || []).length === 7, 'navigation principale contient les 7 destinations demandées');
assert(nav.includes('data-tab="learn"') && nav.includes('<span class="tab-label">Accueil</span>'), 'Accueil reste la première destination');
assert(nav.includes('data-tab="planning"') && nav.includes('<span class="tab-label">Parcours</span>'), 'Parcours est accessible directement');
assert(nav.includes('data-tab="defis"') && nav.includes('<span class="tab-label">Défis</span>'), 'Défis est accessible directement');
assert(nav.includes('data-tab="notes"') && nav.includes('<span class="tab-label tab-label-stack"><span>Mes</span><span>notes</span></span>'), 'Mes notes devient un onglet permanent sur deux lignes');
assert(nav.includes('data-tab="collection"') && nav.includes('<span class="tab-label tab-label-stack"><span>Cartes</span><span>mémo</span></span>'), 'Cartes mémo reste lisible sur deux lignes');
assert(html.includes('id="coll-overview"') && html.includes('coll-overview-ring') && html.includes('aria-label="${pct}% des cartes débloquées"'), 'Cartes mémo présente la progression globale de la collection');
assert(html.includes('completedModules') && html.includes('Modules complets') && html.includes('À obtenir'), 'statistiques de collection calculées depuis les cartes réellement débloquées');
assert(html.includes("nextLesson=allLessons.find(l=>CARTES[l.id]&&!isUnlocked(l.id))") && html.includes('Prochaine carte') && html.includes('Voir la leçon'), 'prochaine carte reliée à sa leçon réelle');
assert(html.includes('class="coll-module ${complete?\'complete\':\'\'}"') && html.includes("complete?'Validé':count"), 'modules de cartes compacts et explicitement validés');
assert(html.includes("classList.add('collection-static')") && html.includes('.collection-static>.fbar'), 'filtres de cartes changés sans rejouer les animations de page');
assert(nav.includes('data-tab="entretien"') && nav.includes('<span class="tab-label tab-label-stack"><span>Entretien</span><span>SQL</span></span>'), 'Entretien SQL devient un onglet permanent sur deux lignes');
assert(html.includes('ent-readiness-stats') && html.includes('masteredTopics') && html.includes('À retravailler') && html.includes('Thèmes validés'), 'Entretien SQL présente une préparation calculée depuis les réponses réelles');
assert(html.includes('class="ent-group ent-topic${complete?\' complete\':\'\'}"') && html.includes("complete?'Validé'"), 'thèmes d’entretien compacts et explicitement validés');
assert(html.includes('class="ent-mastered-label">Maîtrisée</span>'), 'question maîtrisée porte un statut textuel explicite');
assert(html.includes("classList.add('entretien-static')") && html.includes('.entretien-static>.ent-status'), 'filtres d’entretien changés sans rejouer les animations de page');
assert(nav.includes('data-tab="compte"') && nav.includes('<span class="tab-label tab-label-stack"><span>Mon</span><span>compte</span></span>'), 'Mon compte remplace le menu Plus sur deux lignes');
assert(!nav.includes('data-tab="console"'), 'Console reste accessible depuis l’accueil sans surcharger davantage le dock');
assert(nav.indexOf('data-tab="learn"') < nav.indexOf('data-tab="planning"') && nav.indexOf('data-tab="planning"') < nav.indexOf('data-tab="defis"'), 'ordre Accueil, Parcours, Défis conservé');
assert(html.includes('.tab{font-size:9.5px') && html.includes('.tab{font-size:9.1px'), 'libellés du dock agrandis aux deux tailles mobiles');
assert(html.includes('@media (min-width:481px)') && html.includes('.tab-label{height:21px;min-height:21px}'), 'libellés du dock alignés sur une zone commune en desktop');
const defisRoot = html.slice(html.indexOf('id="scr-defis"'), html.indexOf('id="scr-lesson"'));
const planningRoot = html.slice(html.indexOf('id="scr-planning"'), html.indexOf('id="scr-notes"'));
assert(defisRoot.includes('root-home-back') && planningRoot.includes('root-home-back'), 'Défis et Parcours proposent un retour Accueil explicite');
assert((html.match(/class="home-back root-home-back"/g)||[]).length===5, 'retour Accueil cohérent sur les cinq grandes pages concernées');
assert(html.includes('function returnToHome()') && html.includes("title.focus({preventScroll:true})"), 'retour Accueil centralisé avec restitution accessible du focus');
assert(html.includes("function lessonBackLabel(){return activeTab==='planning'?'Parcours':activeTab==='defis'?'Défis':'Accueil';}"), 'leçon renvoyée vers son écran d’origine avec un libellé clair');
assert(html.includes("label.textContent=focused?'Questions':'Accueil'") && html.includes("focused?'Retour aux questions':'Retour à l’accueil'"), 'Entretien revient aux questions avant de revenir à l’accueil');
assert(html.includes('id="scr-notes"') && html.includes('function renderNotesScreen('), 'Mes notes possède un écran racine dédié');
assert(html.includes('class="notes-overview"') && html.includes('data-notes-count') && html.includes('data-notes-pinned') && html.includes('data-notes-sql'), 'Mes notes présente un tableau de bord calculé depuis le carnet réel');
assert(html.includes("latest?`Dernière modification · ${fmtDate(latest.ts)}`") && html.includes('Prêt pour ta première note'), 'carnet adapte son prochain repère à son contenu');
assert(html.includes("startNotePrompt('Ce que je retiens : ')") && html.includes("startNotePrompt('Requête à revoir : ')") && html.includes("startNotePrompt('Question : ')") , 'carnet vide propose trois amorces pédagogiques');
assert(html.includes('function startNotePrompt(txt){ openNote(null,{txt:txt||\'\'}); }'), 'amorce ouvre directement une note préremplie');
assert(html.includes('.notes-hub.empty .searchbar{display:none}') && html.includes("classList.toggle('empty',!all.length)"), 'recherche masquée tant que le carnet est vide');
assert(html.includes('function homeToolsHTML()') && html.includes('Console SQL') && html.includes('Cartes mémo'), 'raccourcis pratiques ajoutés à l’accueil');
assert(html.includes('<span>Pratique libre</span><h2 id="home-tools-title">Outils</h2>') && !html.includes('id="home-tools-title">Outils</h2><button type="button" onclick="switchTab(\'compte\')">Tout voir'), 'section Outils autonome sans faux lien vers les réglages');
assert(html.includes("switchTab('defis')") && html.includes("switchTab('entretien')"), 'Défis et Entretien restent accessibles depuis les outils');
assert(html.includes('function homePathPreviewHTML(') && html.includes('home-path-progress'), 'aperçu compact du parcours présent');
assert(html.includes("left?'Aujourd’hui':'Séance terminée'") && html.includes('environ ${left*8} min'), 'priorité d’accueil donnée à la charge et à la durée de la séance du jour');
assert(html.includes('class="module home-module ${complete') && html.includes('<summary class="home-module-summary">') && html.includes('Tous les cours'), 'long catalogue remplacé par des modules compacts consultables à la demande');
assert(html.includes('class="lesson-validation"') && html.includes('<em>Validé</em>'), 'chaque leçon terminée porte un libellé Validé explicite');
assert(html.includes("complete?'Toutes les leçons sont validées'") && html.includes('class="home-module-valid">Validé</em>'), 'un module porte Validé uniquement lorsque toutes ses leçons le sont');
assert(html.includes('def-focus-kicker') && html.includes("'Prochain défi'") && html.includes('def-focus-total'), 'Défis met en avant la prochaine action et le nombre restant');
assert(html.includes('def-focus-stats') && html.includes('doneByNiv') && html.includes('Faciles</small>'), 'progression des défis calculée pour chaque difficulté');
assert(html.includes('aria-label="${pct}% des défis réussis"') && html.includes('def-focus-icon'), 'pourcentage global des défis annoncé de façon accessible');
assert(html.includes('class="def-row-valid"') && html.includes('<em>Validé</em>'), 'chaque défi réussi porte un libellé Validé explicite');
assert(html.includes("selectedDone===selected.length?'Niveau validé':'Choisis ton défi'"), 'niveau entier explicitement validé lorsque tous ses défis sont réussis');
assert(html.includes('renderDefis(catalogOnly=false)') && html.includes('renderDefis(true)') && html.includes('def-list-static'), 'changement de difficulté sans reconstruction du bandeau ni animation blanche');
assert(html.includes('function planOverviewHTML(st)') && html.includes('pl-overview-ring') && html.includes('Avancement global') && html.includes('Prochain cap'), 'Parcours présente un résumé global, un pourcentage et la prochaine activité');
assert(html.includes('pl-overview-stats') && html.includes('doneLessons') && html.includes('doneChallenges'), 'statistiques du parcours calculées depuis les leçons et défis réellement validés');
assert(html.includes('Les 7 prochains jours') && html.includes('pl-week-legend') && html.includes('weekComplete'), 'planning hebdomadaire annonce les séances prévues et validées');
assert(html.includes('class="pl-chip-valid"') && html.includes("<i aria-hidden=\"true\">✓</i>Validé"), 'activités terminées explicitement marquées Validé dans le planning');
assert(html.includes('Séance validée') && html.includes('dp-session-valid'), 'séance complète explicitement marquée validée');
assert(!html.includes('${planManageHTML(p)}'), 'réglage de rythme redondant retiré du bas du parcours');
assert(account.includes('account-identity') && account.includes('Mode sans compte'), 'identité et mode invité sont explicites');
assert(account.includes('Ma progression') && account.includes('account-stats-grid'), 'progression réelle structurée comme un tableau de bord');
assert(account.includes('Niveau actuel') && account.includes('account-level-track') && account.includes('Prochain cap'), 'niveau SQL et prochain palier calculés depuis la progression réelle');
assert(account.includes('Cette semaine') && account.includes('account-week') && account.includes('weekComplete'), 'activité hebdomadaire reliée aux séances du planning');
assert(account.includes('Accomplissements') && account.includes('account-badges') && account.includes('Première requête'), 'badges pédagogiques débloqués par des actions réelles');
assert(account.includes('Objectif du jour') && account.includes('account-goal-ring'), 'objectif du jour utilise les données du planning');
assert(account.includes('Apprentissage') && account.includes('Compte et assistance') && account.includes('Profil et objectif') && account.includes('Données et confidentialité') && account.includes('Aide et prise en main'), 'réglages essentiels regroupés en catégories explicites');
assert(html.includes('function closePlusDetails()') && account.includes('account-sheet-backdrop') && html.includes("querySelectorAll('#scr-compte .plus-details[open]')"), 'réglages détaillés ouverts dans un seul panneau focalisé et refermable');
assert(account.includes('Mode local actif') && account.includes('Connexion optionnelle'), 'stockage local expliqué clairement');
assert(!account.includes('acc-premium') && !account.includes('4,99 €'), 'fausse offre Premium retirée du parcours de production');
assert(html.includes("const OB_PROFILE_SLIDES=['name','goal','level','practice','rhythm']") && onboarding.includes("const steps=['account',...OB_PROFILE_SLIDES]"), 'onboarding recentré sur 6 étapes utiles');
assert(html.includes("const OB_SLIDES = ['welcome','proof','account','name','goal','level','practice','rhythm','ready']"), 'écran de preuve placé après la bienvenue sans allonger le questionnaire');
assert(onboarding.includes('Monte en niveau,') && onboarding.includes('ob-level-chart') && onboarding.includes('SELECT</span><span>Filtres</span><span>Jointures</span><span>Analyses'), 'progression SQL illustrée par un graphique accessible et des jalons concrets');
assert(onboarding.includes('<strong>74</strong>') && onboarding.includes('<strong>25</strong>') && onboarding.includes('<strong>10 000+</strong><span>requêtes vérifiées en test'), 'preuves chiffrées reliées au contenu réel et aux tests plutôt qu’à de faux utilisateurs');
assert(onboarding.includes('Étape ${active+1} sur ${steps.length}') && onboarding.includes('const remaining='), 'étape et durée restante annoncées dynamiquement');
assert(onboarding.includes('Garde ta progression.') && onboarding.includes('Continuer sans compte'), 'choix du compte clair et mode invité prioritaire');
assert(onboarding.includes('authReady') && onboarding.includes('<small>Bientôt</small>'), 'fournisseurs indisponibles présentés honnêtement');
assert(onboarding.includes('Mode local et privé') && onboarding.includes('Progression sauvegardée sur cet appareil.'), 'bénéfice du mode local explicité');
assert(html.includes('function obRunPractice()') && onboarding.includes('Ta première requête.') && html.includes('db.exec("SELECT id, nom, ville FROM clients WHERE ville = \'Paris\' ORDER BY id;")'), 'premier succès SQL exécuté sur la vraie base pendant l’onboarding');
assert(onboarding.includes('Ta première semaine') && onboarding.includes('Première leçon'), 'écran final enrichi avec un plan de départ concret');
assert(html.includes('@media (prefers-reduced-motion:reduce)') && html.includes('.plus-details-body'), 'nouvelles micro-interactions respectent la réduction des mouvements');
const primaryKeyLesson = html.slice(html.indexOf('{ id:34, titre:"Clé primaire"'), html.indexOf('{ id:35, titre:"Clé étrangère"'));
assert(primaryKeyLesson.includes("WHERE nom = 'Nathan';") && primaryKeyLesson.includes('SQL renvoie <b>2 lignes'), 'la leçon Clé primaire exécute et annonce les deux Nathan réels');
assert(html.includes("(4,'Nathan','Paris'") && html.includes("(10,'Nathan','Paris'"), 'les deux Nathan de Paris existent dans les données SQLite');
assert(html.includes('{ id:75, titre:"OFFSET et pagination"') && html.includes('LIMIT 3 OFFSET 3'), 'pagination stable couverte par une leçon complète');
assert(html.includes('{ id:76, titre:"GROUP_CONCAT"') && html.includes('STRING_AGG'), 'agrégation de texte couverte avec ouverture multi-SGBD');
assert(html.includes('{ id:77, titre:"WITH RECURSIVE"') && html.includes('condition d’arrêt'), 'CTE récursives expliquées avec leur garde-fou');
assert(html.includes('{ id:78, titre:"LAG et LEAD"') && html.includes('PARTITION BY client_id'), 'comparaison aux lignes voisines couverte');
assert(html.includes('{ id:79, titre:"Fenêtres avancées"') && html.includes('UNBOUNDED FOLLOWING') && html.includes('NTILE(4)'), 'cadres et fonctions de fenêtre avancées couverts');
assert(html.includes('{ id:73, titre:"UNION et UNION ALL"') && html.includes('18 lignes : 10 + 8') && !html.includes('17 lignes : 9 + 8'), 'UNION ALL visible et cardinalité corrigée');
assert(html.includes("if(!compact&&learnScreen.scrollTop>72)") && html.includes("else if(compact&&learnScreen.scrollTop<=0)"), 'titre d’accueil stabilisé par deux seuils de défilement');
assert(serviceWorker.includes('requete-2026-09-03-viz-out-reflexe-cles-v269'), 'cache de production renouvelé');

console.log(`\n=== Résultat: ${passed} passés, ${failed} échoués ===\n`);
process.exit(failed ? 1 : 0);
